### ISSUE TITLE
Is there a way to but and sell with this API ?

### ISSUE THREAD

**Issue by transis2** [binance/binance-connector-dotnet#1]
Nice work with this API.

I was wondering whether exist an option to buy and sell inside this API ?

**Comment by tantialex** [comment]
Examples are provided for both CSharp and FSharp.

https://github.com/binance/binance-connector-dotnet/blob/88b4b45ec016ad026cf5e3731132cc198846add2/Examples/CSharp/SpotAccountTrade/NewOrder_Example.cs#L25-L27
