### ISSUE TITLE
Documentation: Where I can get a list for all trading symbols in spot market?

### ISSUE THREAD

**Issue by zydjohnHotmail** [binance/binance-connector-dotnet#23]
### Description

Hello:
I want to know where I can get a list for all trading symbols in spot market.
Like BTCUSDT or others.
If there is no such API endpoints to get the list, having a text file with all the trading symbols is also OK.
Please advise,
Thanks,

**Comment by 2pd** [comment]
https://github.com/binance/binance-connector-dotnet/blob/master/Examples/CSharp/Market/ExchangeInformation_Example.cs
this method can be used to fetch all available trading symbols.

**Comment by zydjohnHotmail** [comment]
OK, thanks!
