### ISSUE TITLE
Documentation: How I can use the repo to find All Coins' Information?

### ISSUE THREAD

**Issue by zydjohnHotmail** [binance/binance-connector-dotnet#27]
### Description

Hello:
I want to find all coin’s information as described in API document, the HTTP Get URL is like this:
GET /sapi/v1/capital/config/getall (HMAC SHA256)

But I can’t find any code example on how to get the information.
I can use NUGET Binance.Spot Version 1.8.0 package to get account balance, since there is some code example.

But how I can do this with the repo?
Please provide some code examples (C# on Windows 10)
Thanks,

**Comment by 2pd** [comment]
https://github.com/binance/binance-connector-dotnet/blob/master/Examples/CSharp/Wallet/AllCoinsInformation_Example.cs

**Comment by zydjohnHotmail** [comment]
Thanks!
