### ISSUE TITLE
Exception : Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by MrElecmen** [binance/binance-connector-dotnet#30]
### Reproduction steps

`var wallet = new Wallet(httpClient: _httpClient, apiKey: user.BinanceApiKey, apiSecret: user.BinanceApiSecret);
string userassets = string.Empty;
try
{
        userassets = await wallet.UserAsset();
}
catch (Exception exception)
{
    throw new Exception(exception.Message);
}`

### Expected behavior

Result should be successfull

### Actual Behavior

Exception : Timestamp for this request was 1000ms ahead of the server's time.

### .NET version

.NET Framework 6.0.x

### Operating system

Windows

**Comment by 2pd** [comment]
Please sync your local time.  If you are working on Linux server,  http://www.ntp.org/ is a very popular tool for that.
