### ISSUE TITLE
Adding support for Self Trade Prevention Mode in Spot Account Trade

### ISSUE THREAD

**Issue by ZacharyDesira** [binance/binance-connector-dotnet#47]
There is no current support in Spot Trading API for Self Trade Prevention. I have pulled the repository and implemented the changes, but I belive I don't have permissions to push them. Is there something that can be done to push such changes? Or is it something that you guys take care of for implementing this?

**Comment by aisling-2** [comment]
@ZacharyDesira Apologies for late reply. You should be able to fork the repository and create a PR for our review.
