### ISSUE TITLE
Binance namespace could not be found

### ISSUE THREAD

**Issue by Tolvic** [binance/binance-connector-dotnet#6]
Installed Binance.Spot 1.0.1 nuget package
Replicated the Websocket example documented in the readme

Encounter this error: "The type or namespace name 'Binance' could not be found."

A repo replicating this error can be found here: https://github.com/Tolvic/BinanceTest

This repo is using .NET core 3.1. I have also tested using .NET 6 and the same error occurs.

**Comment by Tolvic** [comment]
Downgrading to version 1.0.0 resolves this. The issue only appears to be in version 1.0.1

**Comment by tantialex** [comment]
Release 1.0.1 has been deprecated.

All changes have been included in #8
